### ISSUE TITLE
Missing items ?

### ISSUE THREAD

**Issue by fmirault** [AcelisWeaven/AbyssExplorer#12]
Hi !

First of all, thank you for your work 👍 
I found some missing items if I compare with the official wiki (https://neonabyss.gamepedia.com/Items) like the Wings of Wisdom for example.

I really don't know where you found all the data, maybe there is already an update compared to the day you made it ?

**Comment by AcelisWeaven** [comment]
Hi @fmirault, thanks that's a good catch!

This seems to be a bug in the way I import the items. Basically, I get all the items from a Collection in the game data, and I then extract all their data (sprite, translations, and some characteristics for weapons).
What happens with the **Wings of Wisdom** is really strange: it has the same translation ID as **Pegasus**. Usually, the translation ID is enough to get the item translations and sprite, but for this item the only thing that changes is the sprite ID.

---

After investigating, it turned out items were actually using their sprite name to get the translation. I've found a pet with the same issue (**Zombie Sister**).
Anyway, it should be fixed now! Thanks for the issue.

**Comment by AcelisWeaven** [comment]
I'm reopening the issue, this fix switched up Black Raven / Messenger.

**Comment by AcelisWeaven** [comment]
This has also been fixed. What may happen here is that weapons and items don't reference their sprites the same way.
If you find anything else that I could have missed, please let me know!
