### ISSUE TITLE
Noise new skin

### ISSUE THREAD

**Issue by ShadozoneX** [AcelisWeaven/AbyssExplorer#13]
Hello, i just wanted to let you know that the weapon noise has a different skin than the one on your site. I attached a picture of what it looks like in the game. Hope you having a good day/night! [16030720880233440939507940688917](https://user-images.githubusercontent.com/73087278/96392957-e7f1d500-117a-11eb-8191-ed7ba92239ae.jpg)

**Comment by AcelisWeaven** [comment]
Hello, thanks for the report!
I'll try to fix it soon-ish (I'm on vacations right now!)

I'd just need some information: do you play the Steam beta, or another version?

Thanks!

**Comment by ShadozoneX** [comment]
I have it on steam, sorry for not getting to you sooner.

**Comment by AcelisWeaven** [comment]
Thanks for the report @ShadozoneX ! This has been fixed in the latest update.
I've also reworked the way sprites are built by the app, so this kind of issue will be easier to deal with later.

**Comment by AcelisWeaven** [comment]
Hey @ShadozoneX, just wanted to tell you I'll revert this change, since the weapon skin seems to have changed in the latest stable version of the game (`1.2.5.8RC`).

![image](https://user-images.githubusercontent.com/6735195/103086290-8881cc80-45e4-11eb-861e-12729cb149fa.png)

A possible explanation could be that I've been using the experimental branch (and got the 'new' skin early in the tool)
