### ISSUE TITLE
Bug: Emojis don't seem work

### ISSUE THREAD

**Issue by Glaived** [AcelisWeaven/AbyssExplorer#15]
![image](https://user-images.githubusercontent.com/1835170/98081265-14923600-1e77-11eb-8759-4a45499ce207.png)

**Comment by AcelisWeaven** [comment]
This is a Windows-only issue, we could have three possibilities:
- hope that Windows will someday support flag emojis
- remove the emojis in the list
- use images instead of emojis (not a fan of this solution)

What's your opinion @Glaived ?

**Comment by Glaived** [comment]
I think that if there is no other solution than to go through images, then we might as well use this solution. The idea of using emojis for UX is a good one, and I don't think we should remove emojis for lack of an elegant/simple solution.

**Comment by Glaived** [comment]
https://github.com/twitter/twemoji seems to be a good library, simple and allows the use of images via CDN

[My demo](https://codepen.io/Glaived/pen/MWeqZNK)

**Comment by AcelisWeaven** [comment]
This should have been added in the latest version!
Since I had to change how the projects icons were bundled, and since I didn't want to use a CDN to allow offline use, I resized and included the Twemoji files directly.

Here's how it looks:
![image](https://user-images.githubusercontent.com/6735195/98475200-fd947080-21f5-11eb-8ec5-4a85b72973b3.png)

Thanks @Glaived !
