### ISSUE TITLE
Improvement for the Abyss Explorer

### ISSUE THREAD

**Issue by banbo0** [AcelisWeaven/AbyssExplorer#9]
![image](https://user-images.githubusercontent.com/68721037/88356785-03457380-cd37-11ea-8bba-704d922493e5.png)
You could add stuff like that where it shows they weapon type, fire rate, output(would say normal like 80% of the time), and notes/ special things the gun has. The possible things it could say for output are Invisible Bullets, Shurikens, Penetrating Bullets, Laser, Bullets, Small Lasers, Strong Bullets, Tracking Bullets, Rockets, Fishbones, Bullets/Lasers, Normal, Laser Beam, Electric, Boomerang, Bouncy, Small Lasers, Homing Rockets, Tracking Bullets, Stars, Music Notes, and Helix Bullets. this my be to much work but the wiki is missing pictures and when you see a gun in the shop it is hard to find because it does not give you the name.

**Comment by AcelisWeaven** [comment]
Hi @banbo0 ! Thanks for the suggestion, I'm working on a new way to get item data automatically, and getting information like this may be possible.

I'll keep you updated!

**Comment by AcelisWeaven** [comment]
Hey @banbo0, just wanted to let you know that I've made a lot of progress to retrieve useful data about the weapons.

Each weapon is made of a graph of functions and I can extract some data, namely:
- the rate of fire
- the type of bullets fired (laser, bouncy, notes, tracking)
- does it need charging
- does it follow a curve
It'll probably need some fine-tuning but I think it should cover most cases.
There are some outputs like helix bullets that can't be inferred directly, since it's in fact a weapon with a laser and a curve.
In the future I'd like to have some user-contributed notes so it may fit here, like "this weapon has a good synergy with this item". I'll probably ask for some help when it's ready!

Also, I've found some weapons in the wiki that I can't find in the game files, like April. I don't know if this is an error on the wiki or if I can't find the data.
Anyway, I've got a lot of work remaining before I can release this feature, but I think it'll improve the explorer a lot.

**Comment by banbo0** [comment]
ok thanks for the response glad to see it is being added because once it is
done it will be better then the wiki.

**Comment by AcelisWeaven** [comment]
@banbo0 Aaaaand... it's done! You should be able to see it.
![image](https://user-images.githubusercontent.com/6735195/88703661-46279280-d10d-11ea-81a8-6a54ef4accd1.png)

I'll close the issue for now, but if you see any miss-labelling please tell me. Thanks again for the suggestion.
